name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: dev
          POSTGRES_USER: root
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Install sqlx-cli
      run: cargo install sqlx-cli
    - name: Apply migrations
      run: sqlx migrate run --source=db/migrations
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
